# Generated by Django 3.2.12 on 2022-06-16 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("requisitionform", "0002_requisition_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="requisition",
            old_name="type",
            new_name="requisition_type",
        ),
    ]
