# Generated by Django 3.2.12 on 2022-06-16 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requisitions', '0003_rename_type_requisition_requisition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
