# Generated by Django 3.2.5 on 2022-04-20 11:26

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("requestform", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="state",
            field=django_fsm.FSMField(default="new", max_length=50),
        ),
    ]
