# Generated by Django 3.2.5 on 2022-04-28 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("requestform", "0004_remove_request_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="is_budget_approved",
        ),
    ]
