# Generated by Django 3.2.5 on 2022-05-03 08:26

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("requestform", "0005_remove_request_is_budget_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="budget_from",
        ),
        migrations.AddField(
            model_name="request",
            name="budget",
            field=models.CharField(
                blank=True,
                choices=[("Project", "Project"), ("Department", "Department")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[(0, "dummy")],
                db_index=True,
                default="PENDING",
                max_length=100,
                no_check_for_status=True,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="description",
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="request",
            name="type",
            field=models.CharField(
                choices=[("Item", "Item"), ("Service", "Service")],
                default="Item",
                max_length=7,
            ),
        ),
    ]
